// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drivers.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_drivers_991968c43a634355, []int{0}
}

type DriverOptions struct {
	BoolOptions        map[string]bool         `protobuf:"bytes,1,rep,name=bool_options,json=boolOptions" json:"bool_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringOptions      map[string]string       `protobuf:"bytes,2,rep,name=string_options,json=stringOptions" json:"string_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntOptions         map[string]int64        `protobuf:"bytes,3,rep,name=int_options,json=intOptions" json:"int_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringSliceOptions map[string]*StringSlice `protobuf:"bytes,4,rep,name=string_slice_options,json=stringSliceOptions" json:"string_slice_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *DriverOptions) Reset()         { *m = DriverOptions{} }
func (m *DriverOptions) String() string { return proto.CompactTextString(m) }
func (*DriverOptions) ProtoMessage()    {}
func (*DriverOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_drivers_991968c43a634355, []int{1}
}

func (m *DriverOptions) GetBoolOptions() map[string]bool {
	if m != nil {
		return m.BoolOptions
	}
	return nil
}

func (m *DriverOptions) GetStringOptions() map[string]string {
	if m != nil {
		return m.StringOptions
	}
	return nil
}

func (m *DriverOptions) GetIntOptions() map[string]int64 {
	if m != nil {
		return m.IntOptions
	}
	return nil
}

func (m *DriverOptions) GetStringSliceOptions() map[string]*StringSlice {
	if m != nil {
		return m.StringSliceOptions
	}
	return nil
}

type StringSlice struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *StringSlice) Reset()         { *m = StringSlice{} }
func (m *StringSlice) String() string { return proto.CompactTextString(m) }
func (*StringSlice) ProtoMessage()    {}
func (*StringSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_drivers_991968c43a634355, []int{2}
}

func (m *StringSlice) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type ClusterInfo struct {
	Version             string            `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	ServiceAccountToken string            `protobuf:"bytes,2,opt,name=service_account_token,json=serviceAccountToken" json:"service_account_token,omitempty"`
	Endpoint            string            `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
	Username            string            `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	Password            string            `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	RootCaCertificate   string            `protobuf:"bytes,6,opt,name=root_ca_certificate,json=rootCaCertificate" json:"root_ca_certificate,omitempty"`
	ClientCertificate   string            `protobuf:"bytes,7,opt,name=client_certificate,json=clientCertificate" json:"client_certificate,omitempty"`
	ClientKey           string            `protobuf:"bytes,8,opt,name=client_key,json=clientKey" json:"client_key,omitempty"`
	NodeCount           int64             `protobuf:"varint,9,opt,name=node_count,json=nodeCount" json:"node_count,omitempty"`
	Metadata            map[string]string `protobuf:"bytes,10,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status              string            `protobuf:"bytes,11,opt,name=status" json:"status,omitempty"`
}

func (m *ClusterInfo) Reset()         { *m = ClusterInfo{} }
func (m *ClusterInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterInfo) ProtoMessage()    {}
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_drivers_991968c43a634355, []int{3}
}

func (m *ClusterInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClusterInfo) GetServiceAccountToken() string {
	if m != nil {
		return m.ServiceAccountToken
	}
	return ""
}

func (m *ClusterInfo) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ClusterInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ClusterInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ClusterInfo) GetRootCaCertificate() string {
	if m != nil {
		return m.RootCaCertificate
	}
	return ""
}

func (m *ClusterInfo) GetClientCertificate() string {
	if m != nil {
		return m.ClientCertificate
	}
	return ""
}

func (m *ClusterInfo) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *ClusterInfo) GetNodeCount() int64 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func (m *ClusterInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ClusterInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdateRequest struct {
	ClusterInfo   *ClusterInfo   `protobuf:"bytes,1,opt,name=cluster_info,json=clusterInfo" json:"cluster_info,omitempty"`
	DriverOptions *DriverOptions `protobuf:"bytes,2,opt,name=driver_options,json=driverOptions" json:"driver_options,omitempty"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_drivers_991968c43a634355, []int{4}
}

func (m *UpdateRequest) GetClusterInfo() *ClusterInfo {
	if m != nil {
		return m.ClusterInfo
	}
	return nil
}

func (m *UpdateRequest) GetDriverOptions() *DriverOptions {
	if m != nil {
		return m.DriverOptions
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "types.Empty")
	proto.RegisterType((*DriverOptions)(nil), "types.DriverOptions")
	proto.RegisterType((*StringSlice)(nil), "types.StringSlice")
	proto.RegisterType((*ClusterInfo)(nil), "types.ClusterInfo")
	proto.RegisterType((*UpdateRequest)(nil), "types.UpdateRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Driver service

type DriverClient interface {
	Create(ctx context.Context, in *DriverOptions, opts ...grpc.CallOption) (*ClusterInfo, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ClusterInfo, error)
	PostCheck(ctx context.Context, in *ClusterInfo, opts ...grpc.CallOption) (*ClusterInfo, error)
	Remove(ctx context.Context, in *ClusterInfo, opts ...grpc.CallOption) (*Empty, error)
}

type driverClient struct {
	cc *grpc.ClientConn
}

func NewDriverClient(cc *grpc.ClientConn) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) Create(ctx context.Context, in *DriverOptions, opts ...grpc.CallOption) (*ClusterInfo, error) {
	out := new(ClusterInfo)
	err := grpc.Invoke(ctx, "/types.Driver/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ClusterInfo, error) {
	out := new(ClusterInfo)
	err := grpc.Invoke(ctx, "/types.Driver/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) PostCheck(ctx context.Context, in *ClusterInfo, opts ...grpc.CallOption) (*ClusterInfo, error) {
	out := new(ClusterInfo)
	err := grpc.Invoke(ctx, "/types.Driver/PostCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Remove(ctx context.Context, in *ClusterInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/types.Driver/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Driver service

type DriverServer interface {
	Create(context.Context, *DriverOptions) (*ClusterInfo, error)
	Update(context.Context, *UpdateRequest) (*ClusterInfo, error)
	PostCheck(context.Context, *ClusterInfo) (*ClusterInfo, error)
	Remove(context.Context, *ClusterInfo) (*Empty, error)
}

func RegisterDriverServer(s *grpc.Server, srv DriverServer) {
	s.RegisterService(&_Driver_serviceDesc, srv)
}

func _Driver_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Driver/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Create(ctx, req.(*DriverOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Driver/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_PostCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).PostCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Driver/PostCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).PostCheck(ctx, req.(*ClusterInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Driver/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Remove(ctx, req.(*ClusterInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Driver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Driver_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Driver_Update_Handler,
		},
		{
			MethodName: "PostCheck",
			Handler:    _Driver_PostCheck_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Driver_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drivers.proto",
}

func init() { proto.RegisterFile("drivers.proto", fileDescriptor_drivers_991968c43a634355) }

var fileDescriptor_drivers_991968c43a634355 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4e,
	0x10, 0xaf, 0x9b, 0x26, 0x4d, 0xc6, 0x4d, 0xff, 0xfd, 0x6f, 0x0b, 0x58, 0x91, 0x90, 0xa2, 0x00,
	0x22, 0x87, 0x92, 0x43, 0xa0, 0x12, 0xa2, 0x80, 0x80, 0x50, 0x89, 0x0a, 0xf1, 0x21, 0x17, 0x0e,
	0x5c, 0x88, 0x5c, 0x67, 0x0a, 0xab, 0x26, 0xbb, 0x66, 0x77, 0x13, 0x94, 0x33, 0x4f, 0xc9, 0x89,
	0x17, 0xe0, 0x21, 0xd0, 0x7e, 0xc4, 0x59, 0xb7, 0x0e, 0x15, 0xb7, 0xcc, 0xfc, 0x3e, 0x3c, 0x33,
	0x3b, 0x19, 0x68, 0x8e, 0x04, 0x9d, 0xa1, 0x90, 0xbd, 0x4c, 0x70, 0xc5, 0x49, 0x55, 0xcd, 0x33,
	0x94, 0x9d, 0x4d, 0xa8, 0x1e, 0x4d, 0x32, 0x35, 0xef, 0xfc, 0xde, 0x80, 0xe6, 0x4b, 0xc3, 0x78,
	0x97, 0x29, 0xca, 0x99, 0x24, 0xaf, 0x60, 0xeb, 0x94, 0xf3, 0xf1, 0x90, 0xdb, 0x38, 0x0a, 0xda,
	0x95, 0x6e, 0xd8, 0xbf, 0xd3, 0x33, 0xc2, 0x5e, 0x81, 0xdb, 0x7b, 0xc1, 0xf9, 0xd8, 0xfd, 0x3e,
	0x62, 0x4a, 0xcc, 0xe3, 0xf0, 0x74, 0x99, 0x21, 0x6f, 0x61, 0x5b, 0x2a, 0x41, 0xd9, 0x97, 0xdc,
	0x6b, 0xdd, 0x78, 0xdd, 0x2d, 0xf5, 0x3a, 0x31, 0xd4, 0x82, 0x5b, 0x53, 0xfa, 0x39, 0x72, 0x04,
	0x21, 0x65, 0x2a, 0x37, 0xab, 0x18, 0xb3, 0xdb, 0xa5, 0x66, 0xc7, 0x4c, 0x15, 0x9c, 0x80, 0xe6,
	0x09, 0xf2, 0x19, 0xf6, 0x5c, 0x59, 0x72, 0x4c, 0x53, 0xcc, 0xfd, 0x36, 0x8c, 0xdf, 0xfe, 0x5f,
	0x8a, 0x3b, 0xd1, 0xfc, 0x82, 0x2f, 0x91, 0x97, 0x80, 0xd6, 0x53, 0xd8, 0xb9, 0x38, 0x17, 0xb2,
	0x03, 0x95, 0x73, 0x9c, 0x47, 0x41, 0x3b, 0xe8, 0x36, 0x62, 0xfd, 0x93, 0xec, 0x41, 0x75, 0x96,
	0x8c, 0xa7, 0x18, 0xad, 0xb7, 0x83, 0x6e, 0x3d, 0xb6, 0xc1, 0xa3, 0xf5, 0x87, 0x41, 0xeb, 0x19,
	0x90, 0xcb, 0xb3, 0xb8, 0xca, 0xa1, 0xe1, 0x3b, 0x3c, 0x81, 0xff, 0x2e, 0x0c, 0xe0, 0x2a, 0x79,
	0xc5, 0x97, 0x7f, 0x82, 0x1b, 0x2b, 0xfa, 0x2d, 0xb1, 0xe9, 0xfa, 0x36, 0x61, 0x9f, 0xb8, 0xf1,
	0x79, 0x06, 0x9e, 0x75, 0xe7, 0x16, 0x84, 0x1e, 0xb2, 0xac, 0x41, 0x2f, 0xd9, 0xa2, 0x85, 0xce,
	0xaf, 0x0a, 0x84, 0x83, 0xf1, 0x54, 0x2a, 0x14, 0xc7, 0xec, 0x8c, 0x93, 0x08, 0x36, 0xf5, 0x06,
	0x53, 0xce, 0xdc, 0x87, 0x17, 0x21, 0xe9, 0xc3, 0x35, 0x89, 0x62, 0xa6, 0x5f, 0x31, 0x49, 0x53,
	0x3e, 0x65, 0x6a, 0xa8, 0xf8, 0x39, 0x32, 0x37, 0x92, 0x5d, 0x07, 0x3e, 0xb7, 0xd8, 0x07, 0x0d,
	0x91, 0x16, 0xd4, 0x91, 0x8d, 0x32, 0x4e, 0x99, 0x8a, 0x2a, 0x86, 0x96, 0xc7, 0x1a, 0x9b, 0x4a,
	0x14, 0x2c, 0x99, 0x60, 0xb4, 0x61, 0xb1, 0x45, 0xac, 0xb1, 0x2c, 0x91, 0xf2, 0x3b, 0x17, 0xa3,
	0xa8, 0x6a, 0xb1, 0x45, 0x4c, 0x7a, 0xb0, 0x2b, 0x38, 0x57, 0xc3, 0x34, 0x19, 0xa6, 0x28, 0x14,
	0x3d, 0xa3, 0x69, 0xa2, 0x30, 0xaa, 0x19, 0xda, 0xff, 0x1a, 0x1a, 0x24, 0x83, 0x25, 0x40, 0xee,
	0x01, 0x49, 0xc7, 0x14, 0x99, 0x2a, 0xd0, 0x37, 0x2d, 0xdd, 0x22, 0x3e, 0xfd, 0x26, 0x80, 0xa3,
	0xeb, 0xe1, 0xd7, 0x0d, 0xad, 0x61, 0x33, 0xaf, 0x71, 0xae, 0x61, 0xc6, 0x47, 0x38, 0x34, 0x4d,
	0x46, 0x0d, 0xf3, 0x9c, 0x0d, 0x9d, 0x19, 0xe8, 0x04, 0x79, 0x0c, 0xf5, 0x09, 0xaa, 0x64, 0x94,
	0xa8, 0x24, 0x02, 0xb3, 0xe3, 0x6d, 0xf7, 0x48, 0xde, 0x90, 0x7b, 0x6f, 0x1c, 0xc5, 0xee, 0x75,
	0xae, 0x20, 0xd7, 0xa1, 0x26, 0x55, 0xa2, 0xa6, 0x32, 0x0a, 0xcd, 0x77, 0x5d, 0xd4, 0x3a, 0x84,
	0x66, 0x41, 0xf2, 0x2f, 0x0b, 0xda, 0xf9, 0x11, 0x40, 0xf3, 0x63, 0x36, 0x4a, 0x14, 0xc6, 0xf8,
	0x6d, 0x8a, 0x52, 0x91, 0x03, 0xd8, 0x4a, 0x6d, 0x35, 0x43, 0xca, 0xce, 0xb8, 0xb1, 0x59, 0x6e,
	0x93, 0x57, 0x68, 0x1c, 0xa6, 0xde, 0x6a, 0x1c, 0xc2, 0xb6, 0xbd, 0x6f, 0xde, 0x89, 0xd1, 0xc2,
	0xbd, 0xb2, 0x7f, 0x71, 0xec, 0x6e, 0xa1, 0x0b, 0xfb, 0x3f, 0x03, 0xa8, 0x59, 0x02, 0x79, 0x00,
	0xb5, 0x81, 0x40, 0x3d, 0xeb, 0x52, 0x65, 0xab, 0xa4, 0x90, 0xce, 0x9a, 0x56, 0xd9, 0x2e, 0x72,
	0x55, 0xa1, 0xa9, 0x15, 0xaa, 0x03, 0x68, 0xbc, 0xe7, 0x52, 0x0d, 0xbe, 0x62, 0x7a, 0x4e, 0x4a,
	0x28, 0x2b, 0x64, 0xfb, 0x50, 0x8b, 0x71, 0xc2, 0x67, 0x58, 0xaa, 0xd9, 0x72, 0x39, 0x7b, 0xd5,
	0xd7, 0x4e, 0x6b, 0xe6, 0xdc, 0xdf, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x80, 0x62, 0xae, 0x9b,
	0xff, 0x05, 0x00, 0x00,
}
